POST http://localhost:3000/logs HTTP/1.1
content-type: application/json

{
    "level": "info",
    "message": "sample message",
    "context": "sample context",
    "timestamp": "2025-05-15T18:27:50.000Z"
}